# config.yaml

preprocessing:

  outliers:
    strategies:
      - none
      - clip
    thresholds:
      - 2.0
      - 3.0
      - 4.0

  encoding:
    features:
      Month:
        strategy: ordinal
        params:
          order_map:
            January: 1
            February: 2
            March: 3
            April: 4
            May: 5
            June: 6
            July: 7
            August: 8
            September: 9
            October: 10
            November: 11
            December: 12
            Unknown: 0
      #  City:
      #    strategy: one-hot      
      Street:
        strategy: frequency      
      Occupation:
        strategy: frequency
      Credit_Mix:
        strategy: ordinal
        alternatives:
          - frequency
        params:
          order_map:
            Bad: 1
            Standard: 2
            Good: 3
            _: 0
            Unknown: 0      
      Payment_of_Min_Amount:
        strategy: one-hot
        alternatives:
          - frequency
          - ordinal
  
  target_balancing:
   smote:
    sampling_strategy:
     - auto
     - not majority
    k_neighbors:
     - 3
     - 5
     - 7



models:
 xgboost:
  n_estimators: 
   - 300
   - 500
   - 700
  max_depth:
   - 5
   - 7
   - 9
  learning_rate:
   - 0.1
   - 0.05
   - 0.01
  subsample:
   - 0.5
   - 0.7
   - 0.9
  colsample_bytree:
   - 0.7
   - 0.9
   - 1.0
  min_child_weight:
   - 3
   - 5
   - 7
  gamma:
   - 0
   - 0.1
   - 0.2
   - 0.3


  random_forest:
    n_estimators:
      - 100
      - 200
      - 300
    max_depth:
      - null
      - 10
      - 20
      - 30
    